//-------------------------------------------------------------------------------------------
//    THE NVL Maker——GUI Editor for Kirikiri/KAG
//    Copyright (C) 2011  VariableD <wang.siying@gmail.com>

//    You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <http://www.gnu.org/licenses/>.     
//-------------------------------------------------------------------------------------------
//--------------------------------------------------------------------
//这是每个TAG对应的跳转到的文件名表
//--------------------------------------------------------------------
%[
//--------------------------------------------------------------------
//文字篇
//--------------------------------------------------------------------
//对话框
"dia"=>"dia",
"scr"=>"dia",
"menu"=>"dia",
"hidemes"=>"dia",
"showmes"=>"dia",
"framein"=>"dia",
"frameout"=>"dia",

//文字速度
"nowait"=>"nowait",
"endnowait"=>"nowait",

//文字样式
"style"=>"style",

//等待
"wait"=>"wait",
"waitclick"=>"wait",

//输入对话
"_talk"=>"talk",
//批量文本
"_msg"=>"msg",

//文本标记
"l"=>"talkmark",
"r"=>"talkmark",
"lr"=>"talkmark",
"w"=>"talkmark",
"resetfont"=>"talkmark",
"commit"=>"commit",

//NPC姓名
"npc"=>"npc",
//事件跳转
"jump"=>"jump",
"call"=>"call",
"return"=>"return",
//插入标签
"_label"=>"label",
//--------------------------------------------------------------------
//图象篇
//--------------------------------------------------------------------
//显示背景
"bg"=>"bg",
//显示人物
"fg"=>"fg",
//显示头像
"face"=>"face",
//消除背景
"clbg"=>"clbg",
//消除人物/头像
"clfg"=>"clfg",
//--------------------------------------------------------------------
//音乐篇
//--------------------------------------------------------------------
//播放音乐
"bgm"=>"bgm",
//播放音效
"se"=>"se",
//等待音效
"ws"=>"ws",

"vo"=>"vo",
"mv"=>"mv",

//停止音乐
"stopbgm"=>"stopbgm",
"fadebgm"=>"stopbgm",
"fadeoutbgm"=>"stopbgm",

//停止音效
"stopse"=>"stopse",
"fadese"=>"stopse",
"fadeoutse"=>"stopse",

//--------------------------------------------------------------------
//按钮篇
//--------------------------------------------------------------------
//准备选择
"selstart"=>"selstart",
//按钮位置
"locate"=>"locate",
//选择按钮
"selbutton"=>"selbutton",
//等待选择
"selend"=>"selend",
//消除选项
"clsel"=>"clsel",
//消除文字
"er"=>"er",
"cm"=>"er",
"ct"=>"er",
//--------------------------------------------------------------------
//地图篇
//--------------------------------------------------------------------
//调用地图
"map"=>"map",
//消除地图
"clmap"=>"clmap",
//调用面板
"edu"=>"edu",
//消除面板
"cledu"=>"cledu",
//登录CG
"addcg"=>"addcg",
"addend"=>"addend",
//--------------------------------------------------------------------
//变数篇
//--------------------------------------------------------------------
//操作变数
"eval"=>"eval",
//显示变数
"emb"=>"emb",

//创建分歧
"newif"=>"newif",

//条件分歧
"if"=>"if",
"elsif"=>"if",

//分歧结束
"else"=>"endif",
"endif"=>"endif",

//离开游戏
"close"=>"close",
"gotostart"=>"close",
//--------------------------------------------------------------------
//其他篇
//--------------------------------------------------------------------
"_remark"=>"remark",
"iscript"=>"iscript",
"history"=>"history",
//--------------------------------------------------------------------
//特效篇
//--------------------------------------------------------------------
"raininit"=>"raininit",
"snowinit"=>"raininit",
"oldmovieinit"=>"raininit",
"sakurainit"=>"raininit",
"foginit"=>"raininit",
"fireflyinit"=>"raininit",

"rainuninit"=>"raininit",
"snowuninit"=>"raininit",
"oldmovieuninit"=>"raininit",
"sakurauninit"=>"raininit",
"foguninit"=>"raininit",
"fireflyuninit"=>"raininit",

"quake"=>"quake",
"wq"=>"wq",
//--------------------------------------------------------------------
//移动/动态篇
//--------------------------------------------------------------------
"movepos"=>"movepos",
"wm"=>"wm",
"action"=>"action",
"wact"=>"wact",
"stopaction"=>"stopaction",
//--------------------------------------------------------------------
//原始图形篇
//--------------------------------------------------------------------
"backlay"=>"backlay",
"image"=>"image",
"freeimage"=>"freeimage",
"trans"=>"trans",
"wt"=>"wt",
]
